### ISSUE TITLE
浏览器代理出错

### ISSUE THREAD

**Issue by Baikeryoyo** [Mr-xn/BurpSuite-collections#3]
net.portswigger.devtools.client as:unable to start browser
![image](https://user-images.githubusercontent.com/57838797/121619705-985e7180-ca9b-11eb-8e44-8b4022331160.png)
这种是什么情况啊

**Comment by Mr-xn** [comment]
> net.portswigger.devtools.client as:unable to start browser

尝试重启burp chrome 或者burp本身，参考[这里](https://blog.csdn.net/weixin_45728976/article/details/109131220)试一下也可以
