### ISSUE TITLE
转载申请

### ISSUE THREAD

**Issue by 7089bat** [Mr-xn/BurpSuite-collections#3]
作者您好，我是小白帽学习之路公众号，想转载您的“渗透测试面试问题2019版.md”这篇文章，会详细注明来源，冒昧提交ISSUE 实在抱歉。

**Comment by 7089bat** [comment]
> 
> 
> 作者您好，我是小白帽学习之路公众号，想转载您的“渗透测试面试问题2019版.md”这篇文章，会详细注明来源，冒昧提交ISSUE 实在抱歉。

**Comment by Mr-xn** [comment]
> 作者您好，我是小白帽学习之路公众号，想转载您的“渗透测试面试问题2019版.md”这篇文章，会详细注明来源，冒昧提交ISSUE 实在抱歉。

OK
