### ISSUE TITLE
自荐收录

### ISSUE THREAD

**Issue by whwlsfb** [Mr-xn/BurpSuite-collections#4]
个人项目：https://github.com/whwlsfb/BurpCrypto

支持多种加密算法的用于爆破前端加密的BurpSuite插件。

**Comment by Mr-xn** [comment]
好的.晚点添加.

**Comment by Mr-xn** [comment]
added [here](https://github.com/Mr-xn/BurpSuite-collections/commit/20d7b9f6adfad1a53c739a81af7ed45619d0a2d3)
