### ISSUE TITLE
你上传的最新版的burp好像不能用，还是显示license不对

### ISSUE THREAD

**Issue by leeolliet** [Mr-xn/BurpSuite-collections#4]
希望解决一下

**Comment by hack2012** [comment]
我这边一直用的好好的哦，你使用2.1.06的loader去生成授权码就ok了。

**Comment by leeolliet** [comment]
生成复制粘贴显示
the supply license key was not recognized,please try re-entering your license key
我的jdk版本是jdk13

**Comment by hack2012** [comment]
> 生成复制粘贴显示
> the supply license key was not recognized,please try re-entering your license key
> 我的jdk版本是jdk13

https://www.waitalone.cn/technology/burplicense.html
建议使用jdk8 181版本。我测试无问题。。

以上，我只是代博主回复，项目非我所有。

**Comment by leeolliet** [comment]
好的，谢谢，我把Java版本换成jdk 8

**Comment by Mr-xn** [comment]
请使用对应的license loader和burp版本，2.0 以前版本请使用JDK8 以后的可以是高版本的
