### ISSUE TITLE
burp里面怎么在proxy or filter 里面搜索中文？

### ISSUE THREAD

**Issue by Gavin0210** [Mr-xn/BurpSuite-collections#6]
burp里面怎么在proxy里面搜索中文？访问百度 filter 搜索百度没结果

**Comment by yinluobing** [comment]
邮件已收到,回头给你回复!
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Mr-xn** [comment]
如果是filter 可以将中文keyword使用utf-8格式化后配合正则搜索
<img width="1163" alt="filter" src="https://user-images.githubusercontent.com/18260135/224533052-a89bba80-60c6-4ab2-acf1-26ee7667d10d.png">

**Comment by System88888** [comment]
长期大量收WebShell，联系🛩TG：@System88888
