### ISSUE TITLE
bp安装

### ISSUE THREAD

**Issue by GaoHao1122** [Mr-xn/BurpSuite-collections#7]
好像连接失效了，可以帮助我下载吗？

**Comment by xinghetuandui** [comment]
什么玩意

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

From: ***@***.***>
Sent: 2023年3月28日 12:25
To: ***@***.***>
Cc: ***@***.***>
Subject: [Mr-xn/BurpSuite-collections] bp安装 (Issue #7)


好像连接失效了，可以帮助我下载吗？

―

**Comment by GaoHao1122** [comment]
burp suit下载啊，不过已经解决了，在别的地方






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Mr-xn/BurpSuite-collections"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月28日(星期二) 晚上7:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Mr-xn/BurpSuite-collections] bp安装 (Issue #7)





 什么玩意 
 
 Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986&gt; for Windows 
 
 From: ***@***.***&gt; 
 Sent: 2023年3月28日 12:25 
 To: ***@***.***&gt; 
 Cc: ***@***.***&gt; 
 Subject: [Mr-xn/BurpSuite-collections] bp安装 (Issue #7) 
 
 
 好像连接失效了，可以帮助我下载吗？ 
 
 ―
